### ISSUE TITLE
FF Transform recipes not working.

### ISSUE THREAD

**Issue by Nachtflame** [MaxNeedsSnacks/Interactio#1]
Just discovered the mod, and very interested in the Fluid->Fluid Transformations.  Tried at first with the recipe that I wanted it for, then using the example recipe from your wiki.  Both times getting absolutely zero results. 

Interactio-1.15.2-1.2.0
forge-28.1.111 for MC 1.14.4
for datapack loading/shipping I'm using: **The Loader** by _Sky_Som_ [theloader-1.14.4-1.0.0]

**Comment by MaxNeedsSnacks** [comment]
Hmm, that seems a bit odd, does it throw any sort of errors in console with either of them?

**Comment by MaxNeedsSnacks** [comment]
I just noticed I'm a bit of an idiot, the documentation on the wiki is incorrect.

The item input array is called "items" for F->F and the fluid ingredient is called "input", so the correct recipe would be:

```jsonc
{
  "type": "interactio:fluid_fluid_transform",
  "items": [
    {
      "tag": "minecraft:logs",
      "count": 65
    },
    {
      "tag": "forge:chests",
      "count": 1
    }
  ],
  "input": {
    "tag": "water"
  },
  "result": "lava",
  "consume_items": true
}
```

Sorry for the confusion!

**Comment by Nachtflame** [comment]
Did try with the new format, and got a *working* recipe, that produced no result.  Fluid+Items were consumed with sparkling particle effect, but resulting in <minecraft:air>, not fluid.

Have moved to including buckets in my recipes and making Item Transformation recipes which work perfectly.

**Comment by MaxNeedsSnacks** [comment]
May I ask what fluid you are trying to create through your recipe? I wanna see whether I try to fix this for 1.14 as well before I discontinue that version eventually

**Comment by Nachtflame** [comment]
The target fluid in this case was Oil from Silent's Mechanisms.  Just getting ready to test again with 1.2.1. Will update after testing.

**Comment by Nachtflame** [comment]
No luck at all this time.
Recipe - 
```{
  "type": "interactio:fluid_fluid_transform",
  "items": [
    {
      "item": "minecraft:charcoal",
      "count": 128
    }
  ],
  "input": {
    "fluid": "car:canola_oil"
  },
  "result": "silents_mechanisms:oil",
  "consume_items": true
}
```
![2020-02-15_09 03 30](https://user-images.githubusercontent.com/27873876/74592026-1c046d00-4fd2-11ea-9486-31a2fbd5da25.png)

**Comment by MaxNeedsSnacks** [comment]
Okay, so after some testing, I can tell you the following things:

- It's definitely not an issue with Silent's Mechanisms, I've been able to make recipes that output SM oil just fine
- It doesn't seem to be an issue with the stack size
- I don't think the issue is with my mod here as other fluid inputs seem to work fine on 1.14 (I tried with the recipe below)

```jsonc
{
  "type": "interactio:fluid_fluid_transform",
  "items": [
    {
      "item": "minecraft:charcoal",
      "count": 128
    }
  ],
  "input": {
    "fluid": "industrialforegoing:latex"
  },
  "result": "silents_mechanisms:oil",
  "consume_items": true
}
```

This last part is just an assumption, but I think that either, the Canola Oil from the mod you're using has a different registry name for its fluid form (you can use `/dump_registry fluid` to find out what it is if that is the case), or it doesn't have a default fluid / block state. Unfortunately I can't tell you what the exact issue is without decompiling the mod, which might be against the authors' license, so you might have to ask them about it yourself

**Comment by MaxNeedsSnacks** [comment]
Since I haven't been able to reproduce this in 1.14 userdev unfortunately, I'll keep this issue closed for the moment, but if you find out anything, please feel free to tell me.

(For reference, this is what my current 1.14 userdev instance contains)
![image](https://user-images.githubusercontent.com/12750501/74592897-189ad100-5026-11ea-81df-771d8ad002ea.png)
