### ISSUE TITLE
Fluid transformation not working on server

### ISSUE THREAD

**Issue by mtbrenner** [MaxNeedsSnacks/Interactio#15]
Modpack Q-tech, recipe transforms water block into latex block using a plastic sheet. The recipe works in single player but not on server. The item (plastic sheet) just sits in the water block doing nothing.

Q-tech version 0.4b
Minecraft version 1.15.2
Interactio version 1.15.2-2.0.3

**Comment by MaxNeedsSnacks** [comment]
Thanks for the report, I'll try to figure out what's going on!

**Comment by MaxNeedsSnacks** [comment]
This is weird, this exact recipe seems to be working in userdev just fine

![image](https://user-images.githubusercontent.com/12750501/88399362-0ee07b00-cdc7-11ea-8666-6c33808cc999.png)

![image](https://user-images.githubusercontent.com/12750501/88399386-156ef280-cdc7-11ea-9a84-563ed18260af.png)

Could you check whether the `qtech-int` datapack is loaded on the server? This might a pack issue rather than a mod one

**Comment by mtbrenner** [comment]
Seems to work on a test server instance I just created, so it seems like a specific problem of that server.

**Comment by MaxNeedsSnacks** [comment]
Oh, alright, I might just close this issue then if this is just a one-time thing ^^
