### ISSUE TITLE
Fluid to Fluid Transformation in JEI but not working

### ISSUE THREAD

**Issue by davqvist** [MaxNeedsSnacks/Interactio#2]
Hello,

using Forge 31.1.0 and Interactio 1.2.0
also using this json as a test: https://pastebin.com/LYu9a7hR

The recipe shows correctly in JEI, but when I throw the item in water, nothing happens.
Probably I am doing something wrong, would appreciate some help. Thanks a lot in advance.

**Comment by MaxNeedsSnacks** [comment]
I'm currently still trying to figure out what's wrong myself, but I'll get back to you as soon as I've found anything. This is almost definitely on me though, unfortunately

**Comment by MaxNeedsSnacks** [comment]
Seems like the forge version I've been compiling against for 1.2.0 was too old, so updating that fixed it ^^

It should work now in the latest build, which is gonna be available on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/interactio/files/2882259) soon!

On that note, to anyone else reading this, I haven't been able to properly keep up with testing the mod for 1.14.x versions, so I'm discontinuing support for it starting with release 1.2.2 or 1.3.0, whichever comes first!

If for some reason the recipe still doesn't work (it did in both userdev and my test instance), please feel free to add more details, otherwise I'll be closing this issue within the next few days ^^

**Comment by davqvist** [comment]
Thanks for the quick response and hopefully fix, much appreciated.

**Comment by MaxNeedsSnacks** [comment]
No worries, hope that everything's working out fine now ^^

**Comment by davqvist** [comment]
Fixed, tyvm
