### ISSUE TITLE
Advanced anvil functions

### ISSUE THREAD

**Issue by Wxrlds** [MaxNeedsSnacks/Interactio#56]
It would be nice if we were able to add a damage chance for anvil smashing.
So when crafting one can say that it has a 50% chance to get damage.

Another nice thing would be to make the damage per anvil drop and not per crafting recipe.
So you can craft either let's say 10 stacks at once or only one item but the damage calculation is only applied once.

**Comment by MaxNeedsSnacks** [comment]
The first one is already possible, since you can just pass in a number `0.5` instead of a boolean and it'll damage the anvil with the chance specified ^^ As for the second bit, this'll *probably* be done with the rewrite (which has been taking... a while because I've just had so many other things to focus on :/)
